# version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    command: 
      sh -c "alembic upgrade head &&
             python -m seeder.seed_admin &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - eventease_net

  refresher:
    build: ./backend
    depends_on:
      - backend
    command: python scripts/refresh_data.py
    networks:
      - eventease_net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eventease.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - eventease_net


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: node --max-old-space-size=2048 node_modules/.bin/next dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - eventease_net
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventease
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - eventease_net
volumes:
  db_data:

networks:
  eventease_net:
    driver: bridge