"""add map_image to events

Revision ID: 48bbffbfc7bf
Revises: 85dc5be29756
Create Date: 2025-09-04 10:53:19.487364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bbffbfc7bf'
down_revision: Union[str, Sequence[str], None] = '85dc5be29756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('map_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'map_image')
    # ### end Alembic commands ###
