"""add source and url to events

Revision ID: 5b762ef85826
Revises: fb56312805ee
Create Date: 2025-08-29 16:39:01.148082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b762ef85826'
down_revision: Union[str, Sequence[str], None] = 'fb56312805ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('source', sa.String(), nullable=True))
    op.add_column('events', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'url')
    op.drop_column('events', 'source')
    # ### end Alembic commands ###
